### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by sheepster1** [troykelly/python-dynalite#4]
Hi,
I tried using the library but couldn't understand how to use it properly.
Is there a Documentation / example project that i can look at?
Second, I tried looking at the test.py but the config json is not in the path specified by the const.
Thanks for the contribution

**Comment by ziv1234** [comment]
If you use homeassistant, Troy and I have custom components that use this library to control Dynalite:

https://github.com/troykelly/hassio-component-dynalite

https://github.com/ziv1234/hass_dynalite_component

I don’t believe the test.py is updated. I started writing some unit tests in the tests directory, but these are not functionality tests, so the components can provide you better insights.

I also have another python library dynalite-devices (https://github.com/ziv1234/python-dynalite-devices) that uses python-dynalite and creates user friendly devices, so you could also use it if easier.

**Comment by sheepster1** [comment]
Thanks for the reply!
I'm not looking for a hass component.
the other library looks great but can you supply me with an example config.json?
i manged to connect to my gateway but i'm having trouble with understanding the config format from the code.
